const ROLES=['Administrator','Admin Officer','Account Officer','Head of Operations','Main Instructor','Assistant Instructor','Program Coordinator','Academic Planning Officer'];
const TYPES=['Supplies or Materials','Leave or Absence','Maintenance or Repairs','Financial','General Administrative','Other'];
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
async function user(req,env){const sid=(req.headers.get('cookie')||'').match(/portal_session=([^;]+)/)?.[1];if(!sid)return null;return env.PORTAL_DB.prepare(`SELECT s.id,s.name,s.username,s.role,s.department_id FROM sessions x JOIN staff s ON s.id=x.staff_id WHERE x.id=? AND x.expires_at>CURRENT_TIMESTAMP AND s.active=1`).bind(sid).first()}
const admin=u=>u?.role==='Administrator'; const manager=u=>admin(u)||u?.role==='Head of Operations';
function route(type,role){if(type==='Financial')return'Account Officer';if(type==='Leave or Absence'&&role==='Assistant Instructor')return'Main Instructor';return'Admin Officer'}
export async function onRequest({request,env,params}){try{let p=params.path||'';let u=await user(request,env);if(p==='login'&&request.method==='POST'){let b=await request.json(),s=await env.PORTAL_DB.prepare('SELECT * FROM staff WHERE username=? AND active=1').bind(b.username).first();if(!s||s.password_hash!==b.password)return json({error:'Invalid sign-in details.'},401);let id=crypto.randomUUID(),expiry=new Date(Date.now()+864e5).toISOString();await env.PORTAL_DB.prepare('INSERT INTO sessions(id,staff_id,expires_at) VALUES(?,?,?)').bind(id,s.id,expiry).run();return new Response(JSON.stringify({user:{id:s.id,name:s.name,role:s.role}}),{headers:{'content-type':'application/json','set-cookie':`portal_session=${id}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=86400`}})}
if(p==='logout'){if(u)await env.PORTAL_DB.prepare('DELETE FROM sessions WHERE staff_id=?').bind(u.id).run();return new Response(null,{headers:{'set-cookie':'portal_session=; Path=/; Max-Age=0'}})}if(!u)return json({error:'Sign in required.'},401);
if(p==='me')return json({user:u,roles:ROLES,types:TYPES});
if(p==='departments'){if(request.method==='GET')return json({items:(await env.PORTAL_DB.prepare('SELECT * FROM departments WHERE active=1 ORDER BY name').all()).results});if(!admin(u))return json({error:'Access denied.'},403);let b=await request.json();await env.PORTAL_DB.prepare('INSERT INTO departments(name) VALUES(?)').bind(b.name).run();return json({ok:true},201)}
if(p==='staff'){if(!admin(u))return json({error:'Access denied.'},403);if(request.method==='GET')return json({items:(await env.PORTAL_DB.prepare('SELECT s.id,s.name,s.username,s.role,s.active,d.name department FROM staff s LEFT JOIN departments d ON d.id=s.department_id ORDER BY s.name').all()).results});let b=await request.json();if(!b.name||!b.username||!b.password||!b.role||!b.department_id)return json({error:'Complete all required fields.'},400);await env.PORTAL_DB.prepare('INSERT INTO staff(name,username,password_hash,role,department_id) VALUES(?,?,?,?,?)').bind(b.name,b.username,b.password,b.role,b.department_id).run();return json({ok:true},201)}
if(p==='requests'&&request.method==='POST'){let b=await request.json();if(!b.type||!b.department_id||!b.title||!b.description)return json({error:'Complete all required fields.'},400);let assigned=route(b.type,u.role),r=await env.PORTAL_DB.prepare('INSERT INTO requests(type,department_id,title,description,expected_date,requester_id,assigned_role) VALUES(?,?,?,?,?,?,?)').bind(b.type,b.department_id,b.title,b.description,b.expected_date||null,u.id,assigned).run();await env.PORTAL_DB.prepare('INSERT INTO request_activity(request_id,actor_id,action,details) VALUES(?,?,?,?)').bind(r.meta.last_row_id,u.id,'Submitted',`Routed to ${assigned}`).run();return json({id:r.meta.last_row_id},201)}
if(p==='requests'&&request.method==='GET'){let rows=(await env.PORTAL_DB.prepare(`SELECT r.*,d.name department,requester.name requester,assignee.name assignee FROM requests r JOIN departments d ON d.id=r.department_id JOIN staff requester ON requester.id=r.requester_id LEFT JOIN staff assignee ON assignee.id=r.assignee_id ORDER BY r.created_at DESC`).all()).results;rows=rows.filter(r=>manager(u)||r.requester_id===u.id||r.assignee_id===u.id||r.assigned_role===u.role);return json({items:rows})}
let m=p.match(/^requests\/(\d+)(?:\/(comments|status|forward))?$/);if(m){let id=+m[1],r=await env.PORTAL_DB.prepare('SELECT * FROM requests WHERE id=?').bind(id).first();if(!r)return json({error:'Request not found.'},404);let can=manager(u)||r.requester_id===u.id||r.assignee_id===u.id||r.assigned_role===u.role;if(!can)return json({error:'Access denied.'},403);if(!m[2]&&request.method==='GET'){let comments=(await env.PORTAL_DB.prepare('SELECT c.*,s.name author FROM request_comments c JOIN staff s ON s.id=c.author_id WHERE c.request_id=? ORDER BY c.created_at').bind(id).all()).results,activity=(await env.PORTAL_DB.prepare('SELECT a.*,s.name actor FROM request_activity a LEFT JOIN staff s ON s.id=a.actor_id WHERE a.request_id=? ORDER BY a.created_at').bind(id).all()).results;return json({request:r,comments,activity})}let b=await request.json();if(m[2]==='comments'){if(!b.body?.trim())return json({error:'Comment cannot be empty.'},400);await env.PORTAL_DB.batch([env.PORTAL_DB.prepare('INSERT INTO request_comments(request_id,author_id,body) VALUES(?,?,?)').bind(id,u.id,b.body),env.PORTAL_DB.prepare('INSERT INTO request_activity(request_id,actor_id,action) VALUES(?,?,?)').bind(id,u.id,'Comment added')]);return json({ok:true})}if(m[2]==='status'){if(!(manager(u)||r.assigned_role===u.role||r.assignee_id===u.id))return json({error:'Access denied.'},403);if(b.status==='Declined'&&!b.comment?.trim())return json({error:'A decision comment is required.'},400);let q=[env.PORTAL_DB.prepare('UPDATE requests SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.status,id),env.PORTAL_DB.prepare('INSERT INTO request_activity(request_id,actor_id,action,details) VALUES(?,?,?,?)').bind(id,u.id,'Status changed',b.status)];if(b.comment?.trim())q.push(env.PORTAL_DB.prepare('INSERT INTO request_comments(request_id,author_id,body) VALUES(?,?,?)').bind(id,u.id,b.comment));await env.PORTAL_DB.batch(q);return json({ok:true})}if(m[2]==='forward'){if(r.type!=='Leave or Absence'||u.role!=='Main Instructor')return json({error:'Only a Main Instructor can forward this leave request.'},403);await env.PORTAL_DB.batch([env.PORTAL_DB.prepare("UPDATE requests SET assigned_role='Head of Operations',status='Under Review',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id),env.PORTAL_DB.prepare('INSERT INTO request_activity(request_id,actor_id,action,details) VALUES(?,?,?,?)').bind(id,u.id,'Forwarded','Routed to Head of Operations')]);return json({ok:true})}}
return json({error:'Not found.'},404)}catch(e){return json({error:'The request could not be processed.'},500)}}